import torch
from torch import nn

from .base_path import BasePath
from typing import Tuple, Optional
import numpy as np


class MLPDistpath(BasePath):
    """
    Multilayer Perceptron (MLP) path class for generating geometric paths.

    Args:
        potential (callable): The potential energy function.
        initial_point (torch.Tensor): The initial point of the path.
        final_point (torch.Tensor): The final point of the path.
        n_embed (int, optional): Number of embedding dimensions. Defaults to 32.
        depth (int, optional): Depth of the MLP. Defaults to 3.
        seed (int, optional): Random seed. Defaults to 123.
    """
    def __init__(
        self,
        potential: callable,
        initial_point: torch.tensor,
        final_point: torch.tensor,
        n_embed: int = 32,
        depth: int = 3,
        device: torch.device = None,
        seed: int = 123,
    ):
        super().__init__(
            potential=potential,
            initial_point=initial_point,
            final_point=final_point,
            device=device,
        )
        self.activation = nn.SELU()
        self.n_atoms = self.final_point.shape[-1] // 3
        self.indices = torch.triu_indices(self.n_atoms, self.n_atoms, offset=1)
        input_sizes = [1] + [n_embed]*(depth - 1)
        output_sizes = input_sizes[1:] + [self.indices.shape[-1]]
        # output_sizes = [n_embed]*(depth - 1) + [self.final_point.shape[-1]]
        self.layers = [
            nn.Linear(input_sizes[i//2], output_sizes[i//2]) if i%2 == 0\
            else self.activation\
            for i in range(depth*2 - 1)
        ]
        self.mlp = nn.Sequential(*self.layers)
        self.mlp.to(self.device)

    def geometric_path(self, time: float, *args):
        """
        Generates a geometric path using the MLP.

        Args:
            time (float): Time parameter for generating the path.
            *args: Additional arguments.

        Returns:
            torch.Tensor: The geometric path generated by the MLP.
        """
        # print("time", time.shape)

        initial = self.geo_to_dist(self.initial_point).pow(-1)
        final = self.geo_to_dist(self.final_point).pow(-1)
        # initial = self.initial_point
        # final = self.final_point
        interpolation = self.interpolate(time, initial, final)
        # interpolation = self.geo_to_dist(interpolation).pow(-1)
        # interpolation = self.dist_to_geo(interpolation.pow(-1))

        initial = self.mlp(torch.tensor([[0.]], device=self.device))
        final = self.mlp(torch.tensor([[1.]], device=self.device))
        correction = self.mlp(time) - self.interpolate(time, initial, final)

        geo_path = interpolation + correction
        geo_path = self.dist_to_geo(geo_path.pow(-1))
        return geo_path
        
    
    def interpolate(self, time: torch.tensor, initial: torch.tensor, final: torch.tensor) -> torch.tensor:
        """
        Interpolates between the initial and final points.

        Args:
            time (torch.Tensor): Time parameter for generating the path.
            initial (torch.Tensor): The initial point of the path.
            final (torch.Tensor): The final point of the path.

        Returns:
            torch.Tensor: The interpolated path.
        """
        return (1 - time) * initial + time * final
    
    def geo_to_dist(self, geo_path: torch.tensor) -> torch.tensor:
        """
        Converts a geometric path to a distance path.

        Args:
            geo_path (torch.Tensor): The geometric path.

        Returns:
            torch.Tensor: The distance path.
        """
        geo_path = geo_path.reshape(*geo_path.shape[:-1], self.n_atoms, 3)
        dist_path = torch.norm(geo_path[..., :, None, :] - geo_path[..., None, :, :], dim=-1)
        dist_path = dist_path[..., self.indices[0], self.indices[1]]
        return dist_path
    
    def dist_to_geo(self, dist_path: torch.tensor) -> torch.tensor:
        """
        Converts a distance path to a geometric path.

        Args:
            dist_path (torch.Tensor): The distance path.

        Returns:
            torch.Tensor: The geometric path.
        """
        dist = torch.zeros(*dist_path.shape[:-1], self.n_atoms, self.n_atoms, device=self.device)
        dist[..., self.indices[0], self.indices[1]] = dist_path
        dist[..., self.indices[1], self.indices[0]] = dist_path
        center = torch.eye(self.n_atoms, device=self.device) - 1 / self.n_atoms
        eigvals, eigvecs = torch.linalg.eigh(- 0.5 * center @ (dist ** 2) @ center)
        geo_path = eigvals[..., None, -3:].clamp(min=0).sqrt() * eigvecs[..., :, -3:] 
        geo_path = geo_path * eigvecs[..., [0], -3:].sign()    # only an ad hoc fix for the direction
        geo_path = geo_path.reshape(*geo_path.shape[:-2], -1)
        return geo_path

    """
    def get_path(self, times=None):
        if times is None:
            times = torch.unsqueeze(torch.linspace(0, 1., 1000), -1)
        elif len(times.shape) == 1:
            times = torch.unsqueeze(times, -1)

        geo_path = self.geometric_path(times)
        pes_path = self.potential(geo_path)
        
        return geo_path, pes_path
    """