name: Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Publish release to PyPI
    environment:
      name: pypi
      url: https://pypi.org/p/popcornn
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install build
          pip install .

      - name: Build sdist
        run: python -m build --sdist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
